[ports]
server_port = 3000

[https]
enable_https = false
cert_file = ".env/cert.pem"
key_file = ".env/key.pem"
enable_http_redirection = false

[logging]
log_level = "INFO"
file_logging_enabled = true
file_logging_path = "logs/server.log"
